### PR TITLE
updating site with profile

### PR DESCRIPTION
**Pull request by vsoch**
Hey @monajemi ! Here is the updated site with a quick profile. Since this is the main repo for your organization and it renders from master, you shouldn't need to add the `_site` folder or the `Gemfile.lock` (or the sass cache) to the repository itself. Take a look and let me know if it looks ok!

### CODE REVIEW

**Comment by stats285** [comment]
Thank You Vanessa!

**Comment by stats285** [comment]
Also @vsoch you'd be happy with Monday Oct 9? Date is missing from index.md

**Comment by vsoch** [comment]
thanks @stats285 ! September is going to be busy, so my preference is for as late as can be accommodated! haha.

**Comment by stats285** [comment]
You can also do Oct 23, just after Vicky Stodden talk on reproducibility. You want to do that?
So, 9th or 23rd? Please let me know. Thanks @vsoch My one and only contributor on GitHub :)

**Comment by vsoch** [comment]
That would be perfect (Oct 23rd)! Victoria's talk will put mine in the right perspective, so I can spend more time talking about containers vs. reproducibility.

**Comment by monajemi** [comment]
23 it is then! @vsoch

**Pull request merged**
